### PR TITLE
13 bus component improvement on meters

### LINKED ISSUE #13: BUS Component - Improvement on meters
- Depending on Bus Configuration, disabled "RMS Current Measurements" are used instead deleted it.
RMS Currents

- Include Instantaneous voltage and current measurements

### PR DESCRIPTION
**Pull request by FelipeCSantos**
Closes #13

### CODE REVIEW

**Comment by FelipeCSantos** [comment]
As defined in the issue description, initially, this branch would work on avoiding enable/disable problems on the current measurements. After internal discussions, we decide to try to implement other internal measurements to the component.

A Three-Phase Meter is currently used. The power measurements are RMS_based to split the measurements per phase. The problem with this approach is that all three-phase voltage and currents are needed to calculate the power for single/two-phase Bus configuration. Depending on chosen signals, all measurements are available to the user, but the other measured values not desired are zero (have no influence on the results).

image

An Open/Short Circuit component is used to avoid bad voltage loops and able the compile for non-three-phase configuration:

image

The idea is for another future merge to include single-two-phase meters to this Bus Component, but for now, I think it is functional

**Comment by FelipeCSantos** [comment]
I had some problems assigning external grounds to the zero nodes (0) of the Bus. Without the ground, non-three-phase systems have some problems getting the voltages. So for now I'm using directly a ground for the meters.

image

**Comment by FelipeCSantos** [comment]
I have a .tse and a .cus to facilitate the comparison results

[Test Bus.zip](https://github.com/typhoon-hil/opendss-typhoon-hil-interface/files/10326059/Test.Bus.zip)

image

image

image

image

**Comment by FelipeCSantos** [comment]
before merging it, I think we should discuss this new approach because we will have to update the existing models.

**Review by murilones — APPROVED** [review]
Approving.

**Pull request merged**
