### PR TITLE
Added zero sequence removal feature to CPL mode of operation for 3-ph

### PR DESCRIPTION
**Pull request by NavidA1**
Zero sequence removal now allows the load component in CPL mode to prevent middle point or phase voltage drift. This particularly helps cases such as the 3-ph CPL being connected to delta config transformers where there are no constraints on individual phases, but voltage difference between phases.
Also Fixed a bug that prevented compilation when CIL was switched to CPL with different slow and fast execution rates.

### CODE REVIEW

**Comment by murilones** [comment]
Closes #72

**Comment by murilones** [comment]
It seems that the CPL load injects some disturbances on the grid, for example, see the figure and other files attached.
image
[test_load.zip](https://github.com/typhoon-hil/opendss-typhoon-hil-interface/files/10493044/test_load.zip)

**Comment by NavidA1** [comment]
> It seems that the CPL load injects some disturbances on the grid, for example, see the figure and other files attached. image [test_load.zip](https://github.com/typhoon-hil/opendss-typhoon-hil-interface/files/10493044/test_load.zip)

I am running the model, yet don't see the small oscillations. Only observation I can make is that the small oscillations in the posted pic seem to have a 300us period, same as the slow execution rate set for the load.

When I run the attached system, I get this response:
image

**Comment by NavidA1** [comment]
The oscillation issue is now fixed. In single phase CPL block the C-code in charge of super sampling, uses an internal variable Ts (which is the name of one of its input ports) to do calculations, it was renamed to execution_rate and calculations was not being done correctly.

**Comment by murilones** [comment]
Cleaned up the model when setting the zero-sequence removal algorithm. During the process investigated a few other things. The load is behaving as expected on time domain, but it does have a 1% error when compared to OpenDSS. Further improvements on this performance can be dealt with on another merge request. This one is ready to be approved.

**Review by marcosmcc — APPROVED** [review]

**Pull request merged**
